#! /bin/sh

## Bspwm config directory
BSPDIR="$HOME/.config/bspwm"
CURRENT_WALLPAPER="/home/kifni/data/Wallpapers/Favorites/george-hiles-ed-hLWaknyk-unsplash.jpg"

# Colors
background='#2E3440'
foreground='#D8DEE9'
cursor='#D8DEE9'

color0='#3B4252'
color1='#BF616A'
color2='#A3BE8C'
color3='#EBCB8B'
color4='#81A1C1'
color5='#B48EAD'
color6='#88C0D0'
color7='#E5E9F0'
color8='#4C566A'
color9='#BF616A'
color10='#A3BE8C'
color11='#EBCB8B'
color12='#81A1C1'
color13='#B48EAD'
color14='#8FBCBB'
color15='#ECEFF4'

## Get the colors from theme file
FOREGROUND="$foreground"
BACKGROUND="$background"
CURSOR="$cursor"
BLACK="$color0"
RED="$color1"
GREEN="$color2"
YELLOW="$color3"
BLUE="$color4"
MAGENTA="$color5"
CYAN="$color6"
WHITE="$color7"
ALTBLACK="$color8"
ALTRED="$color9"
ALTGREEN="$color10"
ALTYELLOW="$color11"
ALTBLUE="$color12"
ALTMAGENTA="$color13"
ALTCYAN="$color14"
ALTWHITE="$color15"

## Bspwm appearance


## Apply bspwm configurations
bspc config border_width 3
bspc config window_gap 5
bspc config split_ratio 0.5

bspc config focused_border_color "$CYAN" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true


## Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1

pgrep -x sxhkd > /dev/null || sxhkd &
# bspc config remove_disabled_monitors true
# bspc config remove_unplugged_monitor true



laptop=false
laptop_name=eDP-1
external=false
external_name=DP-1


for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
	if [[ $m == "eDP-1" ]]; then
		laptop=true
	elif [[ $m == "DP-1" ]]; then
		external=true
	fi
done

if $laptop && $external; then 
	# bspc monitor $external_name -d 6 7 8 9 10
	# bspc monitor $laptop_name -d 1 2 3 4 5
	nn=0
	for m in `bspc query -M --names`; do
		if [[ $nn == 0 ]];then
			bspc monitor $m -d 1 2 3 4 5
		else
			bspc monitor $m -d 6 7 8 9 10
		fi
		# if [[ $m == $laptop_name ]]; then
		# 	bspc monitor $m -d 6 7 8 9 10
		# else
		# 	bspc monitor $m -d 1 2 3 4 5
		# fi
		let nn++
	done
else
	for m in `bspc query -M --names`; do
		bspc monitor $m -d 1 2 3 4 5
	done
fi

# bspc monitor -n 'DP-1' -d 1 2 3 4 5 6 7 8 9 10

# if [[ $(xrandr --listactivemonitors | grep '  DP-1') ]]; then
#     # bspc monitor "DP-1" -d 1 2 3 4 5
# 	if [[ $(xrandr --listactivemonitors | grep 'eDP-1') ]]; then
#     	# bspc monitor -n 'eDP-1' -d 6 7 8 9 10
# 		for monitor in `bspc query -M`; do
# 			bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5', '6', '7', '8', '9', '10'
# 			let name++
# 		done
# 	fi
# else
# 	 bspc monitor -d 1 2 3 4 5
# fi

# if [[ $(xrandr --listactivemonitors | grep 'eDP-1') ]]; then
#     bspc monitor -n 'DP-1' -d 1 2 3 4 5 6 7 8 9
# fi


# active_monitor=$(xrandr --listactivemonitors)
# readarray -d " " -t strarr <<< "$active_monitor"
# monitor_code=${strarr[${#strarr[*]}-1]}


# bspc monitor -n "$monitor_code" -d '1' '2' '3' '4' '5'

# workspaces() {
# 	# active_monitor=$(xrandr --listactivemonitors)
# 	# readarray -d " " -t strarr <<< "$active_monitor"
# 	# monitor_code=${strarr[${#strarr[*]}-1]}

# 	# bspc monitor -n "$monitor_code" -d '1' '2' '3' '4' '5'
# 	name=1
# 	for monitor in `bspc query -M`; do
# 		bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5', '6', '7', '8', '9', '10'

# 		let name++
# 	done
# }
# workspaces

# bspc monitor -d 1 2 3 4 5

# remove all rules first
bspc rule -r *:*

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a '' desktop=any state=floating

declare -a floating=(alacritty-float Pcmanfm Thunar Onboard Yad 'Firefox:Places' \
Viewnior Nm-connection-editor Blueberry.py Blueman-manager Pavucontrol flameshot Gitk Nm-connection-editor feh)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

bspc rule -a '*:*:Picture in picture' desktop=any state=floating


#tdrop rule
bspc rule -a "tdrop" state=floating center=true focus=on
# Lauch keybindings daemon
sxhkd -c $HOME/.config/sxhkd/sxhkdrc &


# Terminate already running bar instances
killall -q polybar
# killall -q nm-applet
killall -q pasystray

# Restore wallpaper
feh --no-fehbg --bg-fill "$CURRENT_WALLPAPER"

# Wait until the processes have been shut down

# while pgrep -u $UID -x nm-applet >/dev/null; do sleep 1; done
# while pgrep -u $UID -x pasystray >/dev/null; do sleep 1; done
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
# Launch Polybar, using default config location ~/.config/polybar/config


if $laptop; then 
	MONITOR=$laptop_name polybar  archx1polybar &
fi

if $external; then 
	MONITOR=$external_name polybar  archx1polybar &
fi

nm-applet &
blueman-applet &
pasystray &

wmname LG3D


# Fix cursor
xsetroot -cursor_name left_ptr






